interface:
  type: server_openai
  host: "0.0.0.0"
  port: 6001
  
model:
  model_name: "openai/gpt-oss-20b"
  cache_dir: "/tmp/model_cache"  # Use /tmp for cache in Azure ML
  max_batch_size: 1
  
  # Optimized loader configuration
  loader_type: optimized_loader
  optimizations:
    # Baseline configuration - no optimizations
    use_mxfp4: false
    use_flash_attention_3: false  # No Flash Attention for baseline
    use_megablocks_moe: false
    torch_dtype: "auto"
    device_map: "auto"
  
  conversion:
    type: onnx
    output_path: "/tmp/models/gpt_oss_20b_moe_only.onnx"  # Use /tmp for intermediate files
    onnx_export:
      opset_version: 14
      use_dynamic_axes: true
      input_names: ["input_ids"]
      output_names: ["logits"]
      export_sequence_length: 2048

client:
  type: speed_benchmark
  num_requests: 50
  concurrent_requests: 1
  prompt_length: 100
  max_tokens: 100
  temperature: 0.0
  output: "/tmp/benchmark_results/gpt_oss_20b_moe_only_benchmark.json"

benchmark_metadata:
  model_variant: "gpt-oss-20b"
  description: "Benchmark of GPT-OSS-20B with no mxfp4 or flash attention 3"
  purpose: "Isolate MoE kernel performance impact"
